# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProductSearchApp' do
  use_frameworks!

    pod 'lottie-ios'
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'

  target 'ProductSearchAppTests' do
    inherit! :search_paths
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

end
